# Since we create our own virtualens via Tox, don't use any of Travis-CI Python templates/features
language: generic

# Ubuntu 18.04 ships with Python 3.6
dist: bionic

# Don't run tests on WIP branches
branches:
  except:
    - /^WIP-.*$/

services:
  - docker

jobs:
  include:
    - stage: Build Docker image
      script: docker build --pull --tag rdiff-backup-dev:debian-sid .
    - stage: Static tests
      script: docker run --rm -i -v ${PWD}/..:/build -w /build/rdiff-backup rdiff-backup-dev:debian-sid tox -c tox.ini -e flake8
    - stage: Build
      script: docker run --rm -i -v ${PWD}/..:/build -w /build/rdiff-backup rdiff-backup-dev:debian-sid ./setup.py build
    - stage: Run-time tests
      script: docker run --rm -i -v ${PWD}/..:/build -w /build/rdiff-backup rdiff-backup-dev:debian-sid ./run-tests.sh

after_script:
  - pwd
  - ls -la
  - ls -la ..

# Runs in path /home/travis/build/rdiff-backup/rdiff-backup (git repo work directory)
# One level up is an empty directory that can be used for artifacts, cache etc.

cache:
  directories:
    - $HOME/build/rdiff-backup/rdiff-backup_testfiles
