# Since we create our own virtualens via Tox, don't use any of Travis-CI Python templates/features
language: python

# Don't run tests on WIP branches
branches:
  except:
    - /^WIP-.*$/

services:
  - docker

before_script:
  - make container

# Each env becomes a separate job. Add more Python versions to have a matrix.
env:
  - MAKE_STEP=test-static
  - MAKE_STEP=build
  - MAKE_STEP=test-runtime-base
  - MAKE_STEP=test-runtime-root
  - MAKE_STEP=test-runtime-slow

matrix:
  allow_failures:
    - env: MAKE_STEP=test-static

script: make $MAKE_STEP

# Runs in path /home/travis/build/rdiff-backup/rdiff-backup (git repo work directory)
# One level up is an empty directory that can be used for artifacts, cache etc.

# Travis-CI cannot cache the plain testfiles due to permission errors
cache:
  directories:
    - $HOME/build/rdiff-backup/cache
