# Ubuntu 18.04 ships with Python 3.6
dist: bionic

# Don't run tests on WIP branches
branches:
  except:
    - /^WIP-.*$/

cache:
  directories:
    - $HOME/rdiff-backup/rdiff-backup_testfiles

services:
  - docker

before_script:
  - docker build --pull --tag rdiff-backup-dev:debian-sid .

# Runs in path /home/travis/build/rdiff-backup/rdiff-backup (git repo work directory)
# One level up is an empty directory that can be used for artifacts, cache etc.
script:
  - docker run --rm -i -v ${PWD}/..:/build -w /build/rdiff-backup rdiff-backup-dev:debian-sid tox -c tox.ini -e flake8
  - docker run --rm -i -v ${PWD}/..:/build -w /build/rdiff-backup rdiff-backup-dev:debian-sid ./setup.py build
  - docker run --rm -i -v ${PWD}/..:/build -w /build/rdiff-backup rdiff-backup-dev:debian-sid ./run-tests.sh

after_script:
  - pwd
  - ls -la
  - ls -la ..
