# Since we create our own virtualens via Tox, don't use any of Travis-CI Python templates/features
language: python

# Don't run tests on WIP branches
branches:
  except:
    - /^WIP-.*$/

services:
  - docker

before_script:
  - make container

matrix:
  allow_failures:
    - name: Test code style
      env: MAKE_STEP=test-static
  include:
    - name: Test build
      env: MAKE_STEP=build
    - name: Test runtime base
      env: MAKE_STEP=test-runtime-base
    - name: Test runtime root
      env: MAKE_STEP=test-runtime-root
    - name: Test runtime slow
      env: MAKE_STEP=test-runtime-slow

script: make $MAKE_STEP

# Runs in path /home/travis/build/rdiff-backup/rdiff-backup (git repo work directory)
# One level up is an empty directory that can be used for artifacts, cache etc.

# Travis-CI cannot cache the plain testfiles due to permission errors
cache:
  directories:
    - $HOME/build/rdiff-backup/rdiff-backup_testfiles.tar.gz
