language: python

# Ubuntu 18.04 ships with Python 3.6
dist: bionic

# Don't run tests on WIP branches
branches:
  except:
    - /^WIP-.*$/

services:
  - docker

before_install:
  - pwd
  - ls -la
  - ls -la ..
  - docker build --pull --tag rdiff-backup-dev:debian-sid .

script:
  - pwd
  - ls -la
  - ls -la ..
  - docker run --rm docker run -it -v ${PWD}/..:/build -w /build/rdiff-backup rdiff-backup-dev:debian-sid tox -c tox.ini -e flake8
  - docker run --rm docker run -it -v ${PWD}/..:/build -w /build/rdiff-backup rdiff-backup-dev:debian-sid ./setup.py build
  - docker run --rm docker run -it -v ${PWD}/..:/build -w /build/rdiff-backup rdiff-backup-dev:debian-sid ./run-tests.sh
