# Since we create our own virtualens via Tox, don't use any of Travis-CI Python templates/features
language: python

# Don't run tests on WIP branches
branches:
  except:
    - /^WIP-.*$/

services:
  - docker

before_script:
  - make container

matrix:
  include:
    - env: Test code style
      script: make test-static
    - env: Test build
      script: make build
    - env: Test runtime base
      script: make test-runtime-base
    - env: Test runtime root
      script: make test-runtime-root
    - env: Test runtime slow
      script: make test-runtime-slow

# Runs in path /home/travis/build/rdiff-backup/rdiff-backup (git repo work directory)
# One level up is an empty directory that can be used for artifacts, cache etc.

# Travis-CI cannot cache the plain testfiles due to permission errors
cache:
  directories:
    - $HOME/build/rdiff-backup/rdiff-backup_testfiles.tar.gz
